baseURL = 'https://sebastian-blog.vercel.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableEmoji = true 
paginate = 3

[params]
dateFormat = "Jan 2, 2006"
description = "This is my personal blog"

[taxonomies]
author = "authors"
category = "categories"
